# Welcome to Jekyll!
#

# Site settings
title: Noel
description: Multi-Instrumentalist. Performer. Songwriter
owner: Noel Romero # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/yettipotter
  # github: https://github.com/<username>
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/
  #flickr:
  bandcamp: https://electricdharma.bandcamp.com/releases
  bandcamp: https://dis-ease.bandcamp.com/
  instagram: https://www.instagram.com/_yettipotter/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  soundcloud: https://soundcloud.com/noelromero
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
